name: CI/CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  checks:
    name: Automated Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code ğŸ›
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Dependencies ğŸ’½
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Packages ğŸ“¦
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run ESLint Checks âœ…
        run: yarn lint

#      - name: Run TypeScript Checks âœ…
#        run: yarn type-check

#      - name: Run Jest Tests ğŸ§ª
#        run: yarn test

      - name: Build Gatsby Site âš™ï¸
        run: yarn build

  deployment:
    name: Automated Deployment
    needs: checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code ğŸ›
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy to Vercel ğŸš€
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel --prod --token="${{ secrets.VERCEL_TOKEN }}" \
            -m githubCommitSha="${{ github.sha }}" \
            -m githubCommitAuthorName="${{ github.actor }}" \
            -m githubCommitAuthorLogin="${{ github.actor }}" \
            -m githubDeployment=1 \
            -m githubOrg="${{ github.repository_owner }}" \
            -m githubRepo="${{ github.repository }}" \
            -m githubCommitOrg="${{ github.repository_owner }}" \
            -m githubCommitRepo="${{ github.repository }}" \
            -m githubCommitMessage="${{ github.event.head_commit.message }}" \
            -m githubCommitRef="${{ github.ref }}"
